import Navbar from "./(NavBar)/Navbar.jsx";
import "./globals.css";

export const metadata = {
  title: "Pet Taskmaster",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
