import Navbar from "./(NavBar)/Navbar.jsx";
import Footer from "./components/Footer.jsx";
import "./globals.css";
export const dynamic = "force-dynamic";
export const metadata = {
  title: "Pet Taskmaster",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
